-- ============================================================
-- seed.sql — DEPRECATED
--
-- This file has been replaced by 006_real_data_seed.sql which
-- contains real company data for RO-Logistics & Manufacturing
-- Solutions S.A.
--
-- Run order for a fresh database:
--   1. init.sql
--   2. 002_sections_gamification.sql
--   3. 003_posttype_seed.sql          (optional – legacy post-type content)
--   4. 004_company_pages_seed.sql     (optional – overwritten by 005)
--   5. V6__xp_reward_columns.sql      (adds xp_reward / xp_bonus_first_attempt)
--   6. 006_real_data_seed.sql         ← main real data seed
--
-- docker exec -i edl_postgres psql -U edl_user -d employee_digital_library < db/006_real_data_seed.sql
-- ============================================================
